Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.network "private_network", ip: "192.168.30.11"
  
  config.vm.provider "virtualbox" do |v|
	v.memory = 2048
	v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
     apt-get -y update
     hostnamectl set-hostname node1
   SHELL

end
