Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.33.11"

  config.vm.provider "virtualbox" do |v|
	v.memory = 2056
	v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
     yum -y update
     hostnamectl set-hostname node
   SHELL

end