Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.provider "virtualbox" do |v|
	v.memory = 4096
	v.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
     yum -y update
     hostnamectl set-hostname master
   SHELL

end
