Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "private_network", ip: "192.168.30.10"

# config.vm.network "public_network"

  config.vm.provider "virtualbox" do |v|
	v.memory = 4096
	v.cpus = 6
  end

#config.vm.provision "file", source: "~/downloads/Ansible_Project", destination: "$HOME/vagrant/AP"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get -y update
     hostnamectl set-hostname master
   SHELL
end
